# Generated by Django 4.0.6 on 2022-07-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Comment',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.TextField(default='null'),
        ),
    ]
